export const FETCH_START = 'FETCH_START';
export const FETCH_END = 'FETCH_END';

export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_DATA = 'FETCH_MOVIE_DATA';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

export const FETCH_SINGLE_MOVIE_REQUEST = 'FETCH_SINGLE_MOVIE_REQUEST';
export const FETCH_SINGLE_MOVIE_DATA = 'FETCH_SINGLE_MOVIE_DATA';
export const FETCH_SINGLE_MOVIE_ERROR = 'FETCH_SINGLE_MOVIE_ERROR';

export const FETCH_MOVIE_REVIEW_DATA = 'FETCH_MOVIE_REVIEW_DATA';
export const FETCH_MOVIE_REVIEW_ERROR = 'FETCH_MOVIE_REVIEW_ERROR';

export const FETCH_MOVIE_TRAILER_DATA = 'FETCH_MOVIE_TRAILER_DATA';
export const FETCH_MOVIE_TRAILER_ERROR = 'FETCH_MOVIE_TRAILER_ERROR';
